name: build_windows

# Cancel stale runs
# This will cancel running workflows if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_windows:
    # The type of runner that the job will run on
    runs-on:
      - windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Update the submodules below, doing so here will convert ssh to https
          submodules: false
          fetch-depth: 0
          
      - name: Install ARM GCC Toolchain (arm-none-eabi-gcc)
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        id: arm-none-eabi-gcc-action
        with:
          release: '10.3-2021.10' # <-- The compiler release to use

      # Install GNU make tools with choco package manager
      - name: Install Make
        run: |
          choco install make

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          make debug

          # Make sure we can clean with an empty directory without error
          make clean
          dir

          # Make the default target
          make -j --output-sync=target
          dir
          dir build
          # test -d build

          # Make sure we can clean properly
          make clean
          dir
          # test ! -d build
